### ISSUE TITLE
Should we ask for contact email?

### ISSUE THREAD

**Issue by hellcp** [openSUSE/planet-o-o#1]
We don't have a good way to contact the people adding the feeds here. Should we ask for contact emails just in case we ever need to notify them about broken feed or ask them if they want to continue being featured?

**Comment by cboltz** [comment]
Having some contact data makes sense, but I'd recommend not to put mail addresses in a file hosted publically - the spammers will thank us if we do that ;-)

IMHO the openSUSE username is helpful in many cases (hint: `osc whois` - obviously this will only work for people who logged in to OBS at least once).

In some cases, a `git blame` on `planet.ini` or the `planetsuse/feeds` from the old planet also helps - the commits often include a link to a ticket on progress.o.o.

**Comment by hellcp** [comment]
So just ask everybody to include connect:nickname? That should be easy enough

**Comment by cboltz** [comment]
Sounds like a good idea.
