### ISSUE TITLE
Links to sndirsch blog don't work

### ISSUE THREAD

**Issue by sndirsch** [openSUSE/planet-o-o#57]
Thanks for adding my blog to Planet openSUSE. Unfortunately the links to my blogs don't work.

Check the english blogs
--> https://planet.opensuse.org/en/

--> Stefan's openSUSE Blog

These URLs don't work.
https://planet.opensuse.org/nvidia/2022/06/07/nvidia-opengpu.html
https://planet.opensuse.org/scummvm/2022/06/06/drascula.html

No wonder, the links should be:
https://sndirsch.github.io/nvidia/2022/06/07/nvidia-opengpu.html
https://sndirsch.github.io/scummvm/2022/06/06/drascula.html

**Comment by sndirsch** [comment]
Hmm. I followed the recommendation in https://progress.opensuse.org/issues/64550 to use Github Pages as Blog and register this on Planet openSUSE. So I went ahead and created a blog with github pages/Jekyll and registered it here. And it seems I'm not the only one when looking at planet.ini, e.g.

[mslacken]
  feed     = https://mslacken.github.io/feed.xml
  link     = https://mslacken.github.io/

**Comment by hellcp** [comment]
> @hellcp Would it make sense to (also?) catch this case in the planet code and add the domain if it's missing?

We already have https://github.com/openSUSE/planet-o-o/blob/master/bin/jekyll-planet.rb#L105 for fixing up image urls, it shouldn't be too hard to fix this as well

**Comment by hellcp** [comment]
Pull #59 should now fix this issue as well

**Comment by cboltz** [comment]
I just checked your last article (currently available via https://planet.opensuse.org/page37/index.html) and the title is linked to sndirsch.github.io. Therefore I'll assume the long-merged #59 has fixed this issue, and finally close this issue.
