### ISSUE TITLE
feed not related with openSUSE or GNU/Linux stuff

### ISSUE THREAD

**Issue by victorhck** [openSUSE/planet-o-o#62]
[This blog](https://www.vavai.com/) seems to publish content not related with openSUSE, GNU/Linux or geek stuff.
Don't know if make sense keep it in the planet (IMHO)...

**Comment by Tintedfireglass** [comment]
Created a pull request for the same issue
#67 
:)

**Comment by Tintedfireglass** [comment]
@victorhck the pr hasn't been accepted yet though. so the issue still persists.
