### ISSUE TITLE
no updates since Nov 30th

### ISSUE THREAD

**Issue by victorhck** [openSUSE/planet-o-o#73]
Hello.
Seems that there's no new updates in planet.o.o since Nov 30th (2023)

**Comment by cboltz** [comment]
The VM hosting planet.o.o (jekyll.i.o.o) was moved to a new datacenter that day, which includes a strict firewall.

@tacerus: looks like you need to punch some holes in the firewall so that jekyll can fetch the RSS feeds

**Comment by tacerus** [comment]
Hi,

I permitted HTTP and HTTPS traffic originating from jekyll.i.o.o now and confirmed some of the feeds linked on planet.o.o are reachable from the machine.

Any way to trigger a manual refresh or do we just wait?

**Comment by cboltz** [comment]
The cronjob runs at the full hour (maybe + a few minutes because other jekyll instances get rendered before planet) - which also means planet.o.o was updated since you asked.

**Comment by victorhck** [comment]
thanks!
now seems to be ok, and updated.
greetings

**Comment by tacerus** [comment]
Great news. :)
