### ISSUE TITLE
RSS feed does not contain author

### ISSUE THREAD

**Issue by cboltz** [openSUSE/planet-o-o#8]
rss20.xml  doesn't contain the author of each blog post, which is slightly ;-) suboptimal for the planet feed ;-)

Please add it either as "author" field or as a prefix to the title of each post.

**Comment by hellcp** [comment]
The rss that we have is a representation of how it looked with rawdog. Curiously enough, the "author" field in RSS should be filled out with email address according to the spec, which makes no sense. I kinda wish we used atom nowadays tbh. I will abuse the field for author's name, but I am not particularly happy about it.

**Comment by cboltz** [comment]
Thanks! At least in Akregator, it works as expected - the author gets displayed correctly :-)

BTW: In case you prefer a more standards-compliant way - it seems the old planet.o.o used something like `<title>$author $post_title</title>`
