### ISSUE TITLE
SSL error breaks updating of other blogs

### ISSUE THREAD

**Issue by cboltz** [openSUSE/planet-o-o#83]
Quoting a comment in https://progress.opensuse.org/issues/167296:

> An exception caused by bad ssl configuration prevents all the blogs that come after vinzv's from fetching

Such exceptions should be catched so that they don't affect other blogs.

**Comment by tacerus** [comment]
I have not checked what the actual error is we are observing, but it sounds similar to what was recently repaired in `pluto`: https://github.com/feedreader/pluto/pull/47.

**Comment by hellcp** [comment]
it might be as simple as running `bundler update`

**Comment by cboltz** [comment]
It isn't that easy :-/

The result of `bundler update` is:

    sass-embedded-1.79.3-x86_64-linux-gnu requires ruby version >= 3.2, which is
    incompatible with the current version, 3.1.6

I did a partial revert - keeping minor updates, but reverting major version updates. We'll see in an hour if it works again...

**Comment by cboltz** [comment]
That worked :-)
